### ISSUE TITLE
Mobile Layout

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#105]
This will mainly address responsive layout changes which apply to mobile devices. 

Material Design suggest seven [breakpoint widths](https://material.google.com/layout/responsive-ui.html#) to adapt to. We are going to use two: 480 and 840dp. 
### Small (a phone or a small tablet): 0 - 480

Up to 480dp, the main panel housing the legend can take up the whole width of the page, look nice and no produce too much wasted white space. 
- each panel occupies the whole screen
  - child panels should display a `back` arrow instead of the `close` button in the top-left corner when overlaying their parent panels.
- datapanel is always maximized 
  - split view is removed
  - row/column spacing can be adjusted to allow for more information to be shown in it
- Overview map is removed to free up space
- 10px gutter around panels can be removed to free up move space

|  |  |  |
| --- | --- | --- |
| Main view | Legend | Layer Import |
| ![](http://imgur.com/VKlirpO.png) | ![](http://imgur.com/EhI3K3z.png) | ![](http://imgur.com/Ch08S9m.png) |
| Settings | Datapanel | Details (opend from datapanel) |
| ![](http://imgur.com/TzGU5Sh.png) | ![](http://imgur.com/aJO6EJI.png) | ![](http://imgur.com/rlmTnaj.png) |
| Details (opened from map) |  |  |
| ![](http://imgur.com/xF8itZN.png) |  |  |
### Medium (a big phone or a tablet): 480 - 840

At this size, the main panel will create lots of unused white space if it were to take the full width of the page. In this layout, all panels except the datapanel will remain their default width (350dp).
- child panels should display a `back` arrow instead of the `close` button in the top-left corner when overlaying their parent panels.
- datapanel takes takes the full width of the page
  - split view is removed
  - row/column spacing can be adjusted to allow for more information to be shown in it
  - point details panel originated from the datatable opens as an "expanded" popup
- Overview map is removed to free up space
- 10px gutter around panels can be removed to free up move space

|  |  |  |
| --- | --- | --- |
| Main view | Legend | Settings |
| ![](http://imgur.com/xFPaudo.png) | ![](http://imgur.com/H7MHXCX.png) | ![](http://imgur.com/itPey6q.png) |
| Datapanel | Details (opened from datapanel) | Details (opened from map) |
| ![](http://imgur.com/jU54QYB.png) | ![](http://imgur.com/np7hHhf.png) | ![](http://imgur.com/XXO8KHB.png) |
| Details (opened from map; expaned view) |  |  |
| ![](http://imgur.com/jFbACEB.png) |  |  |
### Large (everything larger): 840 - ∞

Done, thanks!

Material Design suggests three options for growing the layout beyond 1600dp:
- Become center aligned with increased margins
- Remain left aligned while the right margin grows
- Continue to grow while revealing additional content
#### Other consideration for mobile support:
- remove `zoom in/out` controls if touch support is detected (needs Mike's approval) (what if it's a laptop with a touch screen, do we still want to remove zoom controls?)
- provide a safeguard or a user warning when downloading large amounts of data on a mobile device (applies to all layouts)
- enlarge small icons (legend entry flags) and/or increase spacing around them to make tapping them easier (applies to all layouts)
#### Other notes:
- Hover tooltips can't be shown on hover on touch-only devices (for obvious reasons), but they do display on single tap and long press. This is useful for things like legend entry flags (type, user-added, etc.). Not so for for actionable controls - they will activate on both actions. Need to prevent controls from activating on long presses (which still should display a tooltip).
- Angular Dragula seem to start the drag on the long press as well when touch events are detected.
#### Task List:
- [ ] add mobile browser detection script
- [x] update styles to include selected breakpoints (need to research ways to do it)
- [x] small and medium layout: remove overview map
- [x] touch mode: enlarge small icons (legend entry flags) and/or increase spacing around them to make tapping them easier (applies to all layouts)
- [x] touch mode: prevent controls from activating on long presses (which still should display a tooltip).
- [x] change basemap selector to a side navigation component
- [x] small layout: update panels to occupy the whole screen
- [x] small and medium layout: add `back` arrows instead of the `close` buttons in the top-left corner to child panels when overlaying their parent panels.
- [x] small and medium layout: remove split view from datatable 
- [x] small and medium layout: datatable is maximized by default
- [x] small layout: adjust row/column spacing to allow for more data to be visible
- [x] medium layout: update details panel opened from the datatable to open as an "expended" popup
- [x] touch mode[needs decision]: enable drag handles on legend entries
- [x] more...
