### ISSUE TITLE
Image Export - Map + Custom Title + Legend

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#176]
As a user, I want to be able to export the map image so that I can share it in a report or with colleagues.  I should be able to specify a title or have a legend present to better describe the map.  
- [x] User should be able to export the map image
- [x] user can specify a custom title
- [x] user can specify to include a legend
- [x] map image displays map scale
- [x] Option to export map is present in the left menu  
- [x] Configuration file allows for functionality to be disabled, defines the Esri Print Service to use for creating the output

**Comment by dan-bowerman** [comment]
Basic image export for March 31st, enhanced (custom name + legend etc) later on.

**Comment by mweech** [comment]
BLOCKED Need to have legend structure defined and working before we can export any images with a legend.

**Comment by james-rae** [comment]
Code from RAMP v1, might be things that can be stolen
https://github.com/RAMP-PCAR/RAMP-PCAR/blob/develop/src/js/RAMP/Modules/imageExport.js

**Comment by jolevesq** [comment]
@james-rae in RAMP, you hide file based layer in the print. Is it because of IE10 because it works on IE11?

**Comment by AleksueiR** [comment]
File-based layers are included in the export image; they are hidden before a task is sent to the print server, so it doesn't try to render them as well. All file-based and feature layers are SVG and we can add them to the whatever comes back from the print server.

**Comment by AleksueiR** [comment]
@mweech 
If a file-based layer is positioned under a service-based layer, it will be rendered above it in the map export image, since the export image of the file-based layers is merged on top of whatever comes from the print service. Is this a problem?
