### ISSUE TITLE
User Added Layers Component

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#182]
Similar to R1 functionality, this is the interface for adding a service or file based layer to the mapping interface.

- [x] Design UI for new component
- [x] Implement UI (#112)
- [x] Port file loading code from RAMP
- [x] Wire up file loading code to UI
- [x] Port service scraping code into geoApi
- [x] Wire up service code to UI
- [x] Allow for integration of catalogue search functionality at a later date (#208) 
- [ ] Ensure meaningful error messages are provided when a CSV is not well formed (#209 & #210)

Traceability Matrix ID#099 & ID#100.

#### 1. Connect Service
 - user input is not a url
   - show an error message: "This is not a valid URL"
   - disable "continue" button
 - user input is a proper url
   - call geoapi predict function
   - if serviceType "Error" is returned
     - show an error message: "This is not a valid Service URL"
     - disable "continue" button
     - if user modifies input or clicks "cancel" button
       - remove this error message
   - in all other cases proceed to step 2 when user clicks "continue" button

#### 2. Select Service type
  - if the serviceType returned in the step 1 is supported (feature, wms, dynamic, tiles, image), preselect it in the "Service Type" dropdown
    - enable "continue" button
  - if the serviceType is "Unknown", do not make a selection
    - disable "continue" button
  - when user click "continue" button
    - validate that the service type is valid for this service url 
      - if validation fails
        - display an error message: "This is not the service type you are looking for"
      - otherwise proceed to step 3

#### 3. Configure Layer

  a. Feature 
      - "Layer Name" required field is prepopulated with data returned by the prediction function; this is the name which will appear on the corresponding legend entry

  b. Dynamic Layer
      - "Layer Name" required field is prepopulated with data returned by the prediction function; this is the name which will appear on the corresponding legend entry

  c. WMS Layer
      - "Layer Name" required field is prepopulated with data returned by the prediction function; this is the name which will appear on the corresponding legend entry
    - "Layer" required field is a dropdown with a list of available sublayers; user can select one;
    although sublayers are displayed in a flat list, their hierarchy is visualised like this:

    ```
      layer 1
      - layer 2
      layer 3
      - layer 4
      - layer 5
      -- layer 6
    ```

  - if any of the required fields are not filled, disable "continue" button
  - when user clicks "continue", try to build the layer
    - if building process errors,
      - display an error message, hopefully something relevant to why it's not building
    - if building successfull
      - close import stepper

**Comment by AleksueiR** [comment]
Relates #112

**Comment by dan-bowerman** [comment]
Dependency on support for file layer types -- this should get its own its PBI.

**Comment by dan-bowerman** [comment]
From Usability Testing: In R1, users did not understand that the "+" button was to add layers manually, not to seek out new Catalogue datasets. Let's ensure that the R2 implementation clearly spells this out.

**Comment by mweech** [comment]
Removing integrated catalogue search scope.

**Comment by james-rae** [comment]
Service scraping and URL prediction is completed with the exception of supporting WMS layers.
As development of the UI for user added layers has been pushed back, focus on completing this has also been pushed. 
Aly has an idea to improve the prediction process, but involves swapping out the library used to make Web Requests (we currently use ESRI's library, which has proxy issues and does not support HEAD requests)

**Comment by james-rae** [comment]
Mar 21-25 - not touched, still on hold due to no work on UI

**Comment by james-rae** [comment]
Week Mar 28-Apr 1 - not touched, still on hold due to no work on UI

**Comment by AleksueiR** [comment]
User-added layers will be added to the end of their respective sort "groups" (feature layer and everything else).

![sort-groups](https://cloud.githubusercontent.com/assets/2285779/15293416/d6ca69b0-1b55-11e6-8f22-b99ab315b4ae.png)

**Comment by mweech** [comment]
Removed the remaining item #210 and closing epic.
