### ISSUE TITLE
Plugin Support

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#1934]
For all things related to plugins including UI, API, and documentation.

#### FGPV v2.0
- [ ] Finalise how plugins are loaded on a page
- [ ] Fix back to cart plugin for demo purposes
- [ ] Document changes

#### FGPV v2.1
- [ ] Since the viewer no longer has a directly accessible external API, ensure plugin support works well for extracting data from the viewer for use on the host page itself.
- [ ] Implement support for more types of plugins, ideally it should be fairly comprehensive.

#### Plugin Suggestions
Either edit this list directly or open a new issue and include in this epic.

- [ ] Map Coordinates Plugin (refer to the _[original PR](https://github.com/fgpv-vpgf/fgpv-vpgf/pull/1880)_)
