### ISSUE TITLE
V2.0 release prep

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#1948]
- [x] Review release notes, compare with merges/logs, update as needed
    - [x] Initial review
    - [x] Complete daily update notes
- [x] Start semi-weekly builds (Monday, Wednesday)
- [x] Fix urgent bugs as discovered

The release is a `const fortnightAway = new Date(+new Date + 12096e5);`
