### ISSUE TITLE
Centralize Layer Filtering Logic 

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#3055]
Currently, multiple UI controls implement their own respective filtering logic.  This is problematic as it is difficult to coordinate behavior between coordinates such as the datagrid filters, and legend based filters.  To this end, a centralized layer filtering system is proposed.  

Steps to accomplish:

- [x] Propose design for centralized filtering logic (#3062)
- [x] Implement Proof of Concept ( #3116 ) 
- [x] Implement Centralized filtering logic and open pull request for:
    - [x] Code changes ( https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3227 )
    - [x] Documentation changes ( PR # )
- [x] Complete regression testing
