### ISSUE TITLE
Centralize Feature Interactions

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#3056]
Feature interaction code has become spread out and difficult to manage.  Introduction of API features that will manipulate feature interactions via the API require this system to be improved.

Steps to accomplish:

- [ ] Propose design for centralized feature interactions (#3069)
- [ ] Implement Proof of Concept ( #3115 ) 
- [ ] Implement Centralized Feature Interaction and open pull request for:
    - [ ] Code changes ( PR # )
    - [ ] Documentation changes ( PR # )
- [ ] Complete regression testing
