### ISSUE TITLE
Replace Legacy Enhanced Datagrid

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#3058]
Replace existing data table with 2 data tables, a simple HTML5 data table output and a extension with existing enhanced datagrid functionality,

- [x] Determine design for integration of table intention/extensions (#2701)
- [x] Replace enhanced table (#2798)
  - [x] **1.** Missing Features (Misc.) (#3077)
  - [x] **2.** Formatting + Rendering Issues and Enhancements (#3079)
  - [x] **3.** Update Filter Status and Sync Layer Visibility (#3159)
  - [x] **4.** Column filters (#3160)
  - [x] **5.** Details and Zoom To Feature Buttons (#3158)
  - [x] **6.** Mobile Compatibility (#3105)
  - [x] **7.** Accessibility Issues (#3080)
  - [x] **8.** Apply to Map button (#3156)
  - [x] **9.** Column Reordering and Sorting (#3157)
  - [x] **10.** Table should obey config (#3185)
  - [x] **11.** Table should preserve state on reload (#3214)
  - [x] **12.** `enhancedTable` broken in IE (#3209)
  - [x] **13.** date picker for filter (#3121)
  - [x] **14.** Details and Zoom sync with Table Filters (#3234)
  - [x] **15.** Attributes Not Populated on Table Reload (#3235)
  - [x] **16.** Selector Filter Broken on Viewer (#3236)
  - [x] **17.** Minor Filter Bugs (#3240)
  - [x] **18.** Print Function Results in Cut Off Pages, Stubborn Dialog Box (#3238)
  - [x] **19.** Data table user documentation (#3117)
  - [x] **20.** Minor Table Bugs (File Based Layers, WFS) (#3263)
  - [x] **21.** Make Extent Filter Event Trigger More Efficient (#3272)
  - [x] **22.** Extent filter Doesn't apply on table open (#3267)
  - [x] **23.** Datatable button in legend item menu doesn't work (#3281)
  - [x] **24.** Keyboard accessibility issues between filters and grid (#3294)
- [x] Add page to documentation describing two types of data tables, usage scenarios and examples  (#3117)
