### ISSUE TITLE
Create HTML5 table intention

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#3063]
Use case:
Add a lighter weight default datagrid table for viewing the features of a layer.  The datagrid would provide less functionality than the existing "enhanced" datagrid by foregoing features such as search, filtering and table layout customization. 

Acceptance Criteria:
- [x] Should be lightweight with minimal features
- [x] Supports a reduced code footprint by avoiding external libraries. 
- [ ] Includes "Feature Details" shortcut for each row
- [ ] Includes "Zoom to" shortcut for each row
- [ ] the simple table should be able to be opened and closed via toggleDataTable() in the legend api (https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3063#issuecomment-440043971)
- [ ] the simpleTable should respond to layer visibility and symbology toggles (https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3063#issuecomment-440043971)

**Comment by mweech** [comment]
@milesap i've moved this back to  "Needs Analysis".  Can you please describe further the intended use cases and acceptance criteria for the data table intention.  The ... "intention" .. here is to provide a reduced functionality table that does not employ search/filtering and customization of columns as can be found in the enhanced datagrid.

I will spec out the issue with some areas to fill in.

**Comment by ShrutiVellanki** [comment]
Just to add to the TODO: 
- the `simple table` should be able to be opened and closed via `toggleDataTable()` in the `legend api`
- this would be similar to how the `enhancedTable` does it: https://github.com/fgpv-vpgf/plugins/pull/18

**Comment by milesap** [comment]
## Current state

![simple-table](https://user-images.githubusercontent.com/10187181/48794300-893e2b00-ecc7-11e8-86b6-ec39b3a96d16.gif)

## Todos

1. Paging results
2. Column sorting
3. Zoom to & details

## Questions

Why is paging needed? Reason: Performance gain from paging will be slim to none, ramp v2.x uses infinite scroll paging (for performance).

Can column sorting be minimalist, as in a text box containing letters where each letter corresponds to a column and updating letter order updates the table. Reason: UI reordering might introduce external libraries which we are trying to avoid + accessibility still needs to be addressed.

**Comment by mweech** [comment]
Details panel and perhaps zoom to is required for accessibilty.  Simple HTML table intention will be delayed to a later milestone.
