### ISSUE TITLE
Allow Custom Map Export Layout via Plugins

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#3563]
As a web mapping application developer, I would like to be able to customize the layout of maps exported by RAMP.  This would allow me to create layouts that are specific to my application as well as provide greater ability to specify custom titles and text in the exported map.

Original discussion: https://github.com/orgs/fgpv-vpgf/teams/ramp-core/discussions/13

# Approach

Export layout customization will be done through project-specific plugins which can cater to their individual export image requirements. An export plugin is expected to take over the mid-point of the image generation process during export.

Unlike table plugins, an export plugin does not have any UI components (except for possible options added to the export settings panel) and reuses the default export dialogue. Also, an export plugin is not involved in the last stage of merging separate images into a single export file (this includes checking for tainted canvases according to the config options and providing feedback to the user if the image cannot be saved automatically).

This is intended to simplify development of export plugins, since they don't need to generate their own UI (which generally should stay generic) and deal with tainted images. This, however, does not preclude a plugin developer from disabling the default export functionality and writing a full-replacement export plugin with its own custom UI dialogue and image fusion logic.

# High-level workflow

1. An export plugin (**plugin**) registers with RAMP on map load
2. Export is triggered by a user or through the API
3. The export service detects the presence of a **plugin** and halts the default export process
4. The export service passes the `exportComponentsService` to the **plugin**
5. The **plugin** can modify the `exportComponentsService` which is by default controlled through the config 
   1. The **plugin** can add or remove any of the default export components (title, map, mapElements, legend, textblock (*new component*), timestamp)
   2. The **plugin** can modify the configurations of component (for example, specifying the legend width and desired column width; or modifying the existing legend structure (*map.legendBlocks*) to exclude/include certain layers)
   3. The **plugin** can add new, custom generators to the `exportComponentsService` 
   4. The **plugin** can reorder the components to control the image overlap, if necessary
6. The **plugin** executes the `exportComponentsService` to generate export images for corresponding components
7. The **plugin** returns the full size of the export image (this is the size of the canvas where all component images will be placed) to export service
8. The **plugin** returns the generated images to the export service along with their x,y pixel coordinates relative to the full canvas (which creates the desired layout) for the final merging
9. The export service displays images in the export dialog
10. The user is satisfied and triggers the download
11. The export service merges the images into a single canvas and attempts to auto-save the file (depending on the `cleanCanvas` setting it might be impossible if any of the images are tainted)

# Generators

## Text-Block generator

Right now, we only have a footnote text generator which is a plain text generator. We think that the [HTML to Canvas library](https://html2canvas.hertzen.com/) should be able to handle any simple HTML (and maybe even complex HTML, but plugin authors need to ensure the end result matches their expectations) and that we can build a generic **text block** generator to replace the footnote generator. An export plugin can use it several times to generate several text blocks and place them in different sections of the final export image.

Plugins can either import that library themselves or it can be provided internally through RAMP.

## Custom generators

A plugin can add a function returning an SVG/canvas wrapped in a promise to the `exportComponentsService`  to include any arbitrary image (like a watermark or a logo) into the final export image.

# Finer points

- Even though the export service is going to perform the final merging of export images, this does not stop an export plugin from merging images by itself and just returning a single canvas to the export service to "merge" again.
- The order in which a plugin returns component images should be bottom-up - it's easier to figure out what overlaps what in this case, I think. Overlapping of components could be intentional, like when you want your two-layer legend to be displayed on top of the map image, or if you want the scale bar/north arrow to be rendered on the map.
- By default, the export dialog will give the user an option to turn on/off certain export components (based on the config settings). The same behaviour should apply to any custom generators added by a plugin, unless explicitly prohibited.

# Rough Implementation plan (refer to sub-issues)

- [ ] Create a generic Text-Block generator (3 points)

This is important. If we cannot reliably convert HTML into SVG/canvas, we would need to keep the plain-text generator and make export plugins responsible for any fancy text blocks they want to add to the final export image (conceivably, they can do it through the custom generators, but it will be more effort for plugin developers).

- [ ] Allow export plugins to register with the Export Service (2 points)

Use ESPG as example. Use `plugin.feature` to mark plugins as export.

- [ ] Modify the Export Service's default logic to invoke an export plugin if present and accept returned component images (including the overall canvas size and components' relative coordinates) (13 points)

- [ ] Modify the `exportComponentsService` to accept new custom generators and changes to the existing service configuration (which generators should be used and in what order) (5 points)

- [ ] Modify the legend export generator to accept legend with/column number configurations as well as the *legendBlocks* collection from the plugin (5 points)

- [ ] Create a sample export plugin (CCCS request) which renders the map and legend side-by-side, and a text blurb underneath  (8 points)

- [ ] Ensure users are still able to interact with certain components like the `title` component through (or custom component created by a plugin, like a text field), if required - FUTURE FEATURE (8 points)

# Acceptance criteria

- [ ] A Text-Block generator creates a close-enough representation of the source HTML code
- [ ] An export plugin can be registered with RAMP and is activated when the export functionality is engaged
- [ ] An export plugin accepts the `exportComponentsService`  and returns
  - the overall canvas size
  - individual export SVG/canvas images with relative pixel coordinates
- [ ] It is still possible for users to interact with export components like the `title` and modify them
- [ ] **High Protein** Snacks ~~for all dietary restrictions~~ are available in the web-mapping pod

**Comment by mweech** [comment]
For @AleksueiR & @spencerwahl :

> # Implementation plan
> 1. [ ]  Create a generic Text-Block generator (3 points)
> 2. [ ]  Allow export plugins to register with the Export Service (2 points)
> 3. [ ]  Modify the Export Service's default logic to invoke an export plugin if present and accept returned component images (13 points)
> 4. [ ]  Modify the `exportComponentsService` to accept new custom generators and changes to the existing service configuration (which generators should be used and in what order) (5 points)
> 5. [ ]  Modify the legend export generator to accept legend with/column number configurations as well as the _legendBlocks_ collection from the plugin (5 points)
> 6. [ ]  Create a sample export plugin (8 points)
> 7. [ ]  Ensure users are still able to interact with `title` component - FUTURE FEATURE (8 points) 

In keeping with the practice of keeping implementation details to a finer level of detail, please break down the work on 3, 6 & 7 into smaller tasks.  

re: 3.. this seems like a significant amount of effort just to move from a built in function to a plugin, especially with features related to that plugin existing in seperate implementation items (i.e. 4)

re: 6.. 8 points to have a sample that utilizes this functionality seems excessive, but perhaps I am missing some heavy lifting rather than just having a lot of contingency baked in..   

re: 7.. as long as we maintain editing of title in our default output I think we can consider this done. I do not think we should be pursuing the allowance of editable fields in a non-default export scenario (at this time), if we did, it should be accomplished entirely on UI side and parameterized to the export capabilities that would be agnostic on the origin of that input (which means we shouldnt need to do anything to accomodate this now).  i would suggest it should be a result of having a custom UI dialog for print export rather than one that is not editable and only allows download of the output.

**Comment by AleksueiR** [comment]
#3 this point has the most uncertainty in terms of the work that needs to be done, hence the higher estimate. It does seem simple, as you pointed out, to go from internal logic to the plugin logic, bu we are only clear on the starting point for this change, and it's possible there will be a cascade of things that need to be modified. We should get better estimates when start breaking this one down into subtasks.

#6 we were thinking of creating the CCCS export plugin as a sample (or at least a starter for it). Also, 8 points here include contingency for making any tweaks/changes to the modified export service that become apparent after we start building a sample plugin.

#7 this is a good point - if you want editable fields, create your own export dialogue. We can drop this from the implementation plan then.

**Comment by AleksueiR** [comment]
The implementation plan is revised. Please refer to this Epic's sub-issues for detailed breakdown of work.

`Create a sample export plugin (CCCS request)` task is replaced with creating a simple export plugin with just a map image and a watermark. Implementation of the CCCS export plugin should be scoped under that project.
