### ISSUE TITLE
Thematic Maps

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#405]
Provide support for a prescriptive legend structure defined in the viewer configuration.  This would allow for the default hierarchical structure of the map services to be overridden in order to tailor the appearance when publishing a thematic map.
- [x] **[#TM0]** The map author can specify a title for the map via configuration. 
- [x] **[#TM1]** The map author can specify contextual text that would be available in an About the Map panel.
- [REMOVED] **[#TM2]** The map author can specify a url for a basemap entry to get more information on the basemap.
- [x] **[#TM3]** The map author can disable the ability to reorder map layers (for auto-generated legends). 
- [x] **[#TM6]** Legend entries are defined in configuration in the order in which they should initially appear (from top down).  While using JSAPI v3 all raster layers must render under vector layers as this is a limitation of the ESRI API.
- [x] **[#TM7]** An item in the legend is either
    A) A map layer entry
    B) A collection of items
    C) An information section (can be a text block, an image, or an unbound layer)

### Map Layer Entries
- [x] **[#TM8]** A map layer entry can be omitted from appearing as an item in the layer legend (layer will be seen on map, but invisible from layer legend).
- [x] **[#TM9]** A map layer entry can have a description defined which will appear beneath the layer title and above the layer symbology when expanded.
- [x] **[#TM10]** A map layer entry can be specified to not responds to opening the datagrid, 
- [x] **[#TM11]** A map layer entry can have its query control disabled.
- [x] **[#TM12]** By default, the map layer entry symbology and layer entry title is defined by the service legend and service name
- [x] **[#TM13]** The map layer symbology can be overriden in configuration by specifying text and imagery sets.  This can be rendered as icons (as FeatureLayers are currently rendered) or as large images (as WMSes are currently rendered).
- [x] **[#TM14]** The map layer entry title can be overriden in configuration by specifying specific text
- [x] **[#TM15]** The map layer entry can have its visibility toggle disabled.
- [x] **[#TM16]** The map layer entry can have its transparency control disabled.
- [x] **[#TM17]** A map layer may control more than one layer; in this case one layer will be designated as a primary and all other layers as secondary.  Changes made to the primary will be propagated to the secondary layers if possible.  Rendering order will be taken from the main configuration and map layers will only define the bindings for layer controls in this case.
### Collections of Layer Items
- [x] **[#TM18]** A collection of items may contain one or more: layer entries, info sections, visibility sets or collections.
- [x] **[#TM19]** Visibility sets may contain collections and layer entries only.  In a visibility set at most one item will be visible at any time (all items may also be disabled), and only top level items will be affected by this setting (i.e. a collection within a visibility set will not propagate any changes from the visibility set downwards).
- [x] **[#TM20]** Visibility sets will render as a continuous block (it is not possible to have gaps in the visibility set).
- [x] **[#TM21]** A collection of items can have a single transparency control enabled in the settings panel for the group such that it will control the transparency of all layers in its collection.  A child layer can have its specific transparency changed, however subsequent changes at the collection level will override this transparency.
## UI Module Changes
- [x] new template for info sections
- [x] render visibility sets within group
- [x] address template switching (loading, loaded, error)
  - [x] handle placeholder behaviour changes (state transitions remain the same)
- [x] add group visibility and opacity controls
- [x] update settings bindings to refactored LegendEntry
- [x] update flag bindings to refactored LegendEntry

**Comment by alyec** [comment]
Some initial discussions: https://github.com/fgpv-vpgf/fgpv-vpgf/wiki/Config-Schema#structured-legends

**Comment by mweech** [comment]
See https://github.com/fgpv-vpgf/fgpv-vpgf/issues/409#issuecomment-198494829 for relevant functionality.
