### ISSUE TITLE
State Transition Tracking

### ISSUE THREAD

**Issue by alyec** [fgpv-vpgf/fgpv-vpgf#606]
This is a refactoring task for state tracking with the geo module.  Currently states are determine by checking a variety of boolean variables which introduces a lot of complexity in state checking.  This should be replaced by a single location for state tracking (boolean properties reflecting those we currently have can be added as read only for the ui module to consume).  ES6 classes should be used for exposing read only properties.

Suggested tasks:
- [x] convert layer record to an ES6 class
- [x] add a state tracking property
- [x] hook layer events to trigger state transitions using the new property
- [x] expose read only boolean properties for `isLoading`, `isError` and `isPlaceHolder`
- [ ] consolidate discussion on this issue into a wiki page and include a state transition diagram

![state-transition](https://cloud.githubusercontent.com/assets/7646414/15260305/21443806-1924-11e6-9ce6-f98e52ce232d.png)

**Comment by james-rae** [comment]
Does the word `reload` mean the user actively clicks the reload button in the TOC?   If so, should the arrow from Refresh to Loaded be changed to something like `redraw`?

Alternately, if a layer gets stuck in Refresh state and the user clicks reload (i.e. it hasnt errored, but has been waiting for server response for some time), would that be an arrow from Refresh to Loading, labelled `reload`?

**Comment by alyec** [comment]
Yes, reload is an active click.  You may have commented looking at the original diagram I uploaded @spencerwahl noticed that the diagram didn't actually reflect my paper version so I added a new version where the `reload` action from `refresh` goes to `loading` instead of `loaded`.

**Comment by james-rae** [comment]
Yep.  Updated diagram is good :trophy:

**Comment by AleksueiR** [comment]
Let the class also expose `isOutOfScale` read-only property.

**Comment by james-rae** [comment]
How would system set `isOutOfScale`?  A setter function?

**Comment by AleksueiR** [comment]
From the in-pod discussion: out of scale flags are being calculated on every zoom level change and set directly on legend entries. There is no need for the `isOutOfScale` flag on the layer container.
