### ISSUE TITLE
Language management

### ISSUE THREAD

**Issue by ChrisLatRNCan** [fgpv-vpgf/fgpv-vpgf#765]
The one-stop for language management.
Here a list of things to be done/adressed (Please feel free to add/comment).

- [ ] Inventory of language related issues (I'll assigned them to myself if they are not already assigned)

- [ ] Check if we still need a detection routine

- [ ] Document more the language initialization/transition flow (wiki)

- [x] Chase english only stuff (eg. hamburger menu, error message, info coming from services, etc)

- [ ] Have some kind of thesaurus for specific terms for a seamless UX  (wiki)

- [ ] Official review/correction by external translation/traduction org

- [ ] Integration of a set of first nation languages (the most well-document: cree, innuktitut, other ???) a lot of challenge there but worth the effort. We should at lest try with one of them.

**Comment by mweech** [comment]
splitting off remaining child item and closing this epic.  new language related issues can be opened as needed.
