### ISSUE TITLE
Enhanced Datagrid

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#884]
Implement functionality to enhance the capabilities of the Datagrid.

## Develop UI for Filters
Develop the filters UI following the mockups and comments from #1240.
- [x] Global Search
- [x] Button Cluster
     - [x] Apply to Map Button (show when filters changed)
     - [x] Clear Filters
     - [x] Toggle Filters Settings
- [x] Filters Settings Panel
     - [x] Reorder Fields
     - [x] Hide/Display Fields
     - [ ] ~~Set Filters Type~~ (we can't change filter type because definition query will fail)
     - [x] Set Filters Value
     - [x] Set Sorting Fields
- [x] Large Layout (Desktop)
     - [x] Add Filters Row (set filters from Datagrid in addition of filters setting)

## Implements filters functionnalities
- [x] Filter Datagrid by Current Extent
- [x] Clear Filters
- [x] Apply Datagrid Filters to Map (apply filters on map with a definition query)
     - (only works for **service** feature layer (not user added layer like csv) and dynamic service)
- [x] Filter Datagrid by fields
     - [x] String
     - [x] Range numbers (min/max)
     - [x] Range date (date picker)
     - [x] Drop down selection (multiple select)
- [x] Global text search (already available in Datatables, just need to enable and configure)
     - [x] Use Global Search to Type Complex Queries
- [x] Multisort Datagrid (columns.orderData option)
- [x] Reorder Fields (from modification in filters setting)
- [x] Hide/Display Fields (from modification in filters setting)
- [ ] ~~Change Filter Type (from modification in filters setting)~~ (we can't change filter type because definition query will fail)
- [x] Set Sorting Fields (from modification in filters setting)
- [x] Export data contain customized data
     - [x] Only visible column
     - [x] Reorder columns
     - [x] Filter and sort data

## Update Config Schema
Update the config file schema to let _map author_ define a default state for the filters. Those options will be use in a case of a thematic map. The configuration file should be able to set these options:
- [x] Set table open by default
- [x] Set table name
- [x] Hide field
- [x] Set field not searchable
- [x] Set filter type
- [ ] ~~Freeze filter type~~ (we can't change filter type because definition query will fail)
- [x] Set sorting field by default
- [x] Set field name (title)
- [x] Set fields order
- [x] Enable/disable global search for a table
- [x] Set width for a column
- [x] apply the filter to map on load

## Modify Filters to Set Options from Configuration File
- [x] Allow filters to set default parameters (above) from the configuration file

## Load Static File
Be able to load Datagrid data from a json file instead of a layer to speed up process (we had a layer who take near a minute to get the query result). The format for this file is the same as the response from query task (json format).
- [ ] Update Configuration File Schema
- [ ] Read JSON File to Create Datagrid

## Other task
- [x] Determined Progress Bar on Datagrid Attribute Loading (https://github.com/fgpv-vpgf/fgpv-vpgf/issues/613)

## Outside Scope of this Epic
Those functionalities are not intended to be develop in this Epic but we need to think about them when we develop filters so they can _if needed_ be implemented later
- [x] When a text is very long, apply a renderer (...) to limit the numbers of characters shown. Need to be WCAG. Need to work or be disable in mobile.
- [ ] Select an area on the map (bbox or polygon) to filter the Datagrid (spatial filter)
     - In the mean time we have filter by extent
- [ ] Select elements from Datagrid to highlight them on the map (can see the features without      having to zoom in and out)
- [ ] Select multiple elements to zoom to
- [ ] Optional, show linked table info. Show information from an ESRI link table below each record
- [ ] Render field with a URL with a link. In GCViz we have different kind of field who can contain URL (URL, URL with a predefine label value, URL with a label value from another field, ...)
- [ ] Render field whit a picture with a link. In details panel show the picture
- [ ] be able to have the datatable in a div outside the viewer

**Comment by mweech** [comment]
Unlinking issue #1415 from Epic as this can be considered an individual Feature Request.
